[build-system]
requires = ["setuptools>=62", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "pysindy-plume-experiments"
dynamic = ["version"]
dependencies = [
  "mitosis>=0.3.0",
  "pysindy[cvxpy] @ git+https://github.com/dynamicslab/pysindy,
  "matplotlib",
  "pysindy-experiments @ git+https://github.com/Jacob-Stevens-Haas/gen-experiments"
]

[tool.setuptools]
packages=["plumex"]

[tool.setuptools_scm]

